{"name": "test_login_success[YeShen]", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))", "trace": "self = <urllib3.connectionpool.HTTPConnectionPool object at 0x0000023377D15B38>\nmethod = 'POST'\nurl = '/wd/hub/session/10e33678-dbba-4408-85f8-c1354bb255e4/element'\nbody = '{\"using\": \"id\", \"value\": \"com.tnaot.newspro:id/tv_login_btn\"}'\nheaders = {'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Type': 'application/json;charset=UTF-8', 'User-Agent': 'appium/python 1.1.0 (selenium/3.141.0 (python windows))'}\nretries = Retry(total=3, connect=None, read=None, redirect=None, status=None)\nredirect = False, assert_same_host = False\ntimeout = <object object at 0x00000233766DCDF0>, pool_timeout = None\nrelease_conn = True, chunked = False, body_pos = None\nresponse_kw = {'request_url': 'http://127.0.0.1:4726/wd/hub/session/10e33678-dbba-4408-85f8-c1354bb255e4/element'}\nparsed_url = Url(scheme=None, auth=None, host=None, port=None, path='/wd/hub/session/10e33678-dbba-4408-85f8-c1354bb255e4/element', query=None, fragment=None)\ndestination_scheme = None, conn = None, release_this_conn = True\nhttp_tunnel_required = False, err = None, clean_exit = False\n\n    def urlopen(\n        self,\n        method,\n        url,\n        body=None,\n        headers=None,\n        retries=None,\n        redirect=True,\n        assert_same_host=True,\n        timeout=_Default,\n        pool_timeout=None,\n        release_conn=None,\n        chunked=False,\n        body_pos=None,\n        **response_kw\n    ):\n        \"\"\"\n        Get a connection from the pool and perform an HTTP request. This is the\n        lowest level call for making a request, so you'll need to specify all\n        the raw details.\n    \n        .. note::\n    \n           More commonly, it's appropriate to use a convenience method provided\n           by :class:`.RequestMethods`, such as :meth:`request`.\n    \n        .. note::\n    \n           `release_conn` will only behave as expected if\n           `preload_content=False` because we want to make\n           `preload_content=False` the default behaviour someday soon without\n           breaking backwards compatibility.\n    \n        :param method:\n            HTTP request method (such as GET, POST, PUT, etc.)\n    \n        :param url:\n            The URL to perform the request on.\n    \n        :param body:\n            Data to send in the request body, either :class:`str`, :class:`bytes`,\n            an iterable of :class:`str`/:class:`bytes`, or a file-like object.\n    \n        :param headers:\n            Dictionary of custom headers to send, such as User-Agent,\n            If-None-Match, etc. If None, pool headers are used. If provided,\n            these headers completely replace any pool-specific headers.\n    \n        :param retries:\n            Configure the number of retries to allow before raising a\n            :class:`~urllib3.exceptions.MaxRetryError` exception.\n    \n            Pass ``None`` to retry until you receive a response. Pass a\n            :class:`~urllib3.util.retry.Retry` object for fine-grained control\n            over different types of retries.\n            Pass an integer number to retry connection errors that many times,\n            but no other types of errors. Pass zero to never retry.\n    \n            If ``False``, then retries are disabled and any exception is raised\n            immediately. Also, instead of raising a MaxRetryError on redirects,\n            the redirect response will be returned.\n    \n        :type retries: :class:`~urllib3.util.retry.Retry`, False, or an int.\n    \n        :param redirect:\n            If True, automatically handle redirects (status codes 301, 302,\n            303, 307, 308). Each redirect counts as a retry. Disabling retries\n            will disable redirect, too.\n    \n        :param assert_same_host:\n            If ``True``, will make sure that the host of the pool requests is\n            consistent else will raise HostChangedError. When ``False``, you can\n            use the pool on an HTTP proxy and request foreign hosts.\n    \n        :param timeout:\n            If specified, overrides the default timeout for this one\n            request. It may be a float (in seconds) or an instance of\n            :class:`urllib3.util.Timeout`.\n    \n        :param pool_timeout:\n            If set and the pool is set to block=True, then this method will\n            block for ``pool_timeout`` seconds and raise EmptyPoolError if no\n            connection is available within the time period.\n    \n        :param release_conn:\n            If False, then the urlopen call will not release the connection\n            back into the pool once a response is received (but will release if\n            you read the entire contents of the response such as when\n            `preload_content=True`). This is useful if you're not preloading\n            the response's content immediately. You will need to call\n            ``r.release_conn()`` on the response ``r`` to return the connection\n            back into the pool. If None, it takes the value of\n            ``response_kw.get('preload_content', True)``.\n    \n        :param chunked:\n            If True, urllib3 will send the body using chunked transfer\n            encoding. Otherwise, urllib3 will send the body using the standard\n            content-length form. Defaults to False.\n    \n        :param int body_pos:\n            Position to seek to in file-like body in the event of a retry or\n            redirect. Typically this won't need to be set because urllib3 will\n            auto-populate the value when needed.\n    \n        :param \\\\**response_kw:\n            Additional parameters are passed to\n            :meth:`urllib3.response.HTTPResponse.from_httplib`\n        \"\"\"\n    \n        parsed_url = parse_url(url)\n        destination_scheme = parsed_url.scheme\n    \n        if headers is None:\n            headers = self.headers\n    \n        if not isinstance(retries, Retry):\n            retries = Retry.from_int(retries, redirect=redirect, default=self.retries)\n    \n        if release_conn is None:\n            release_conn = response_kw.get(\"preload_content\", True)\n    \n        # Check host\n        if assert_same_host and not self.is_same_host(url):\n            raise HostChangedError(self, url, retries)\n    \n        # Ensure that the URL we're connecting to is properly encoded\n        if url.startswith(\"/\"):\n            url = six.ensure_str(_encode_target(url))\n        else:\n            url = six.ensure_str(parsed_url.url)\n    \n        conn = None\n    \n        # Track whether `conn` needs to be released before\n        # returning/raising/recursing. Update this variable if necessary, and\n        # leave `release_conn` constant throughout the function. That way, if\n        # the function recurses, the original value of `release_conn` will be\n        # passed down into the recursive call, and its value will be respected.\n        #\n        # See issue #651 [1] for details.\n        #\n        # [1] <https://github.com/urllib3/urllib3/issues/651>\n        release_this_conn = release_conn\n    \n        http_tunnel_required = connection_requires_http_tunnel(\n            self.proxy, self.proxy_config, destination_scheme\n        )\n    \n        # Merge the proxy headers. Only done when not using HTTP CONNECT. We\n        # have to copy the headers dict so we can safely change it without those\n        # changes being reflected in anyone else's copy.\n        if not http_tunnel_required:\n            headers = headers.copy()\n            headers.update(self.proxy_headers)\n    \n        # Must keep the exception bound to a separate variable or else Python 3\n        # complains about UnboundLocalError.\n        err = None\n    \n        # Keep track of whether we cleanly exited the except block. This\n        # ensures we do proper cleanup in finally.\n        clean_exit = False\n    \n        # Rewind body position, if needed. Record current position\n        # for future rewinds in the event of a redirect/retry.\n        body_pos = set_file_position(body, body_pos)\n    \n        try:\n            # Request a connection from the queue.\n            timeout_obj = self._get_timeout(timeout)\n            conn = self._get_conn(timeout=pool_timeout)\n    \n            conn.timeout = timeout_obj.connect_timeout\n    \n            is_new_proxy_conn = self.proxy is not None and not getattr(\n                conn, \"sock\", None\n            )\n            if is_new_proxy_conn and http_tunnel_required:\n                self._prepare_proxy(conn)\n    \n            # Make the request on the httplib connection object.\n            httplib_response = self._make_request(\n                conn,\n                method,\n                url,\n                timeout=timeout_obj,\n                body=body,\n                headers=headers,\n>               chunked=chunked,\n            )\n\nvenv\\lib\\site-packages\\urllib3\\connectionpool.py:706: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <urllib3.connectionpool.HTTPConnectionPool object at 0x0000023377D15B38>\nconn = <urllib3.connection.HTTPConnection object at 0x0000023377D15D68>\nmethod = 'POST'\nurl = '/wd/hub/session/10e33678-dbba-4408-85f8-c1354bb255e4/element'\ntimeout = Timeout(connect=<object object at 0x00000233766DC9A0>, read=<object object at 0x00000233766DC9A0>, total=None)\nchunked = False\nhttplib_request_kw = {'body': '{\"using\": \"id\", \"value\": \"com.tnaot.newspro:id/tv_login_btn\"}', 'headers': {'Accept': 'application/json', 'C...tent-Type': 'application/json;charset=UTF-8', 'User-Agent': 'appium/python 1.1.0 (selenium/3.141.0 (python windows))'}}\ntimeout_obj = Timeout(connect=<object object at 0x00000233766DC9A0>, read=<object object at 0x00000233766DC9A0>, total=None)\nread_timeout = <object object at 0x00000233766DC9A0>\n\n    def _make_request(\n        self, conn, method, url, timeout=_Default, chunked=False, **httplib_request_kw\n    ):\n        \"\"\"\n        Perform a request on a given urllib connection object taken from our\n        pool.\n    \n        :param conn:\n            a connection from one of our connection pools\n    \n        :param timeout:\n            Socket timeout in seconds for the request. This can be a\n            float or integer, which will set the same timeout value for\n            the socket connect and the socket read, or an instance of\n            :class:`urllib3.util.Timeout`, which gives you more fine-grained\n            control over your timeouts.\n        \"\"\"\n        self.num_requests += 1\n    \n        timeout_obj = self._get_timeout(timeout)\n        timeout_obj.start_connect()\n        conn.timeout = timeout_obj.connect_timeout\n    \n        # Trigger any extra validation we need to do.\n        try:\n            self._validate_conn(conn)\n        except (SocketTimeout, BaseSSLError) as e:\n            # Py2 raises this as a BaseSSLError, Py3 raises it as socket timeout.\n            self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)\n            raise\n    \n        # conn.request() calls http.client.*.request, not the method in\n        # urllib3.request. It also calls makefile (recv) on the socket.\n        try:\n            if chunked:\n                conn.request_chunked(method, url, **httplib_request_kw)\n            else:\n                conn.request(method, url, **httplib_request_kw)\n    \n        # We are swallowing BrokenPipeError (errno.EPIPE) since the server is\n        # legitimately able to close the connection after sending a valid response.\n        # With this behaviour, the received response is still readable.\n        except BrokenPipeError:\n            # Python 3\n            pass\n        except IOError as e:\n            # Python 2 and macOS/Linux\n            # EPIPE and ESHUTDOWN are BrokenPipeError on Python 2, and EPROTOTYPE is needed on macOS\n            # https://erickt.github.io/blog/2014/11/19/adventures-in-debugging-a-potential-osx-kernel-bug/\n            if e.errno not in {\n                errno.EPIPE,\n                errno.ESHUTDOWN,\n                errno.EPROTOTYPE,\n            }:\n                raise\n    \n        # Reset the timeout for the recv() on the socket\n        read_timeout = timeout_obj.read_timeout\n    \n        # App Engine doesn't have a sock attr\n        if getattr(conn, \"sock\", None):\n            # In Python 3 socket.py will catch EAGAIN and return None when you\n            # try and read into the file pointer created by http.client, which\n            # instead raises a BadStatusLine exception. Instead of catching\n            # the exception and assuming all BadStatusLine exceptions are read\n            # timeouts, check for a zero timeout before making the request.\n            if read_timeout == 0:\n                raise ReadTimeoutError(\n                    self, url, \"Read timed out. (read timeout=%s)\" % read_timeout\n                )\n            if read_timeout is Timeout.DEFAULT_TIMEOUT:\n                conn.sock.settimeout(socket.getdefaulttimeout())\n            else:  # None or a value\n                conn.sock.settimeout(read_timeout)\n    \n        # Receive the response from the server\n        try:\n            try:\n                # Python 2.7, use buffering of HTTP responses\n                httplib_response = conn.getresponse(buffering=True)\n            except TypeError:\n                # Python 3\n                try:\n                    httplib_response = conn.getresponse()\n                except BaseException as e:\n                    # Remove the TypeError from the exception chain in\n                    # Python 3 (including for exceptions like SystemExit).\n                    # Otherwise it looks like a bug in the code.\n>                   six.raise_from(e, None)\n\nvenv\\lib\\site-packages\\urllib3\\connectionpool.py:445: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nvalue = None, from_value = None\n\n>   ???\n\n<string>:3: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <urllib3.connectionpool.HTTPConnectionPool object at 0x0000023377D15B38>\nconn = <urllib3.connection.HTTPConnection object at 0x0000023377D15D68>\nmethod = 'POST'\nurl = '/wd/hub/session/10e33678-dbba-4408-85f8-c1354bb255e4/element'\ntimeout = Timeout(connect=<object object at 0x00000233766DC9A0>, read=<object object at 0x00000233766DC9A0>, total=None)\nchunked = False\nhttplib_request_kw = {'body': '{\"using\": \"id\", \"value\": \"com.tnaot.newspro:id/tv_login_btn\"}', 'headers': {'Accept': 'application/json', 'C...tent-Type': 'application/json;charset=UTF-8', 'User-Agent': 'appium/python 1.1.0 (selenium/3.141.0 (python windows))'}}\ntimeout_obj = Timeout(connect=<object object at 0x00000233766DC9A0>, read=<object object at 0x00000233766DC9A0>, total=None)\nread_timeout = <object object at 0x00000233766DC9A0>\n\n    def _make_request(\n        self, conn, method, url, timeout=_Default, chunked=False, **httplib_request_kw\n    ):\n        \"\"\"\n        Perform a request on a given urllib connection object taken from our\n        pool.\n    \n        :param conn:\n            a connection from one of our connection pools\n    \n        :param timeout:\n            Socket timeout in seconds for the request. This can be a\n            float or integer, which will set the same timeout value for\n            the socket connect and the socket read, or an instance of\n            :class:`urllib3.util.Timeout`, which gives you more fine-grained\n            control over your timeouts.\n        \"\"\"\n        self.num_requests += 1\n    \n        timeout_obj = self._get_timeout(timeout)\n        timeout_obj.start_connect()\n        conn.timeout = timeout_obj.connect_timeout\n    \n        # Trigger any extra validation we need to do.\n        try:\n            self._validate_conn(conn)\n        except (SocketTimeout, BaseSSLError) as e:\n            # Py2 raises this as a BaseSSLError, Py3 raises it as socket timeout.\n            self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)\n            raise\n    \n        # conn.request() calls http.client.*.request, not the method in\n        # urllib3.request. It also calls makefile (recv) on the socket.\n        try:\n            if chunked:\n                conn.request_chunked(method, url, **httplib_request_kw)\n            else:\n                conn.request(method, url, **httplib_request_kw)\n    \n        # We are swallowing BrokenPipeError (errno.EPIPE) since the server is\n        # legitimately able to close the connection after sending a valid response.\n        # With this behaviour, the received response is still readable.\n        except BrokenPipeError:\n            # Python 3\n            pass\n        except IOError as e:\n            # Python 2 and macOS/Linux\n            # EPIPE and ESHUTDOWN are BrokenPipeError on Python 2, and EPROTOTYPE is needed on macOS\n            # https://erickt.github.io/blog/2014/11/19/adventures-in-debugging-a-potential-osx-kernel-bug/\n            if e.errno not in {\n                errno.EPIPE,\n                errno.ESHUTDOWN,\n                errno.EPROTOTYPE,\n            }:\n                raise\n    \n        # Reset the timeout for the recv() on the socket\n        read_timeout = timeout_obj.read_timeout\n    \n        # App Engine doesn't have a sock attr\n        if getattr(conn, \"sock\", None):\n            # In Python 3 socket.py will catch EAGAIN and return None when you\n            # try and read into the file pointer created by http.client, which\n            # instead raises a BadStatusLine exception. Instead of catching\n            # the exception and assuming all BadStatusLine exceptions are read\n            # timeouts, check for a zero timeout before making the request.\n            if read_timeout == 0:\n                raise ReadTimeoutError(\n                    self, url, \"Read timed out. (read timeout=%s)\" % read_timeout\n                )\n            if read_timeout is Timeout.DEFAULT_TIMEOUT:\n                conn.sock.settimeout(socket.getdefaulttimeout())\n            else:  # None or a value\n                conn.sock.settimeout(read_timeout)\n    \n        # Receive the response from the server\n        try:\n            try:\n                # Python 2.7, use buffering of HTTP responses\n                httplib_response = conn.getresponse(buffering=True)\n            except TypeError:\n                # Python 3\n                try:\n>                   httplib_response = conn.getresponse()\n\nvenv\\lib\\site-packages\\urllib3\\connectionpool.py:440: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <urllib3.connection.HTTPConnection object at 0x0000023377D15D68>\n\n    def getresponse(self):\n        \"\"\"Get the response from the server.\n    \n        If the HTTPConnection is in the correct state, returns an\n        instance of HTTPResponse or of whatever object is returned by\n        the response_class variable.\n    \n        If a request has not been sent or if a previous response has\n        not be handled, ResponseNotReady is raised.  If the HTTP\n        response indicates that the connection should be closed, then\n        it will be closed before the response is returned.  When the\n        connection is closed, the underlying socket is closed.\n        \"\"\"\n    \n        # if a prior response has been completed, then forget about it.\n        if self.__response and self.__response.isclosed():\n            self.__response = None\n    \n        # if a prior response exists, then it must be completed (otherwise, we\n        # cannot read this response's header to determine the connection-close\n        # behavior)\n        #\n        # note: if a prior response existed, but was connection-close, then the\n        # socket and response were made independent of this HTTPConnection\n        # object since a new request requires that we open a whole new\n        # connection\n        #\n        # this means the prior response had one of two states:\n        #   1) will_close: this connection was reset and the prior socket and\n        #                  response operate independently\n        #   2) persistent: the response was retained and we await its\n        #                  isclosed() status to become true.\n        #\n        if self.__state != _CS_REQ_SENT or self.__response:\n            raise ResponseNotReady(self.__state)\n    \n        if self.debuglevel > 0:\n            response = self.response_class(self.sock, self.debuglevel,\n                                           method=self._method)\n        else:\n            response = self.response_class(self.sock, method=self._method)\n    \n        try:\n            try:\n>               response.begin()\n\n..\\..\\Python3.7.2\\lib\\http\\client.py:1321: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <http.client.HTTPResponse object at 0x0000023377D15588>\n\n    def begin(self):\n        if self.headers is not None:\n            # we've already started reading the response\n            return\n    \n        # read until we get a non-100 response\n        while True:\n>           version, status, reason = self._read_status()\n\n..\\..\\Python3.7.2\\lib\\http\\client.py:296: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <http.client.HTTPResponse object at 0x0000023377D15588>\n\n    def _read_status(self):\n        line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n        if len(line) > _MAXLINE:\n            raise LineTooLong(\"status line\")\n        if self.debuglevel > 0:\n            print(\"reply:\", repr(line))\n        if not line:\n            # Presumably, the server closed the connection before\n            # sending a valid response.\n>           raise RemoteDisconnected(\"Remote end closed connection without\"\n                                     \" response\")\nE           http.client.RemoteDisconnected: Remote end closed connection without response\n\n..\\..\\Python3.7.2\\lib\\http\\client.py:265: RemoteDisconnected\n\nDuring handling of the above exception, another exception occurred:\n\nself = <TestCases.test_login.TestLogin object at 0x0000023377CDFDD8>\nlogin_common_driver = <appium.webdriver.webdriver.WebDriver (session=\"10e33678-dbba-4408-85f8-c1354bb255e4\")>\n\n    @allure.feature(\"登录模块\")\n    @allure.story(\"登录成功\")\n    @pytest.mark.usefixtures(\"login_common_driver\")\n    def test_login_success(self, login_common_driver):\n        with allure.step(\"正常登录\"):\n            # IndexPage(login_common_driver).click_login()\n            print('-------=========================={}'.format(login_common_driver))\n            time.sleep(5)\n            # rlMine = (By.ID, 'com.tnaot.newspro:id/rlMine')\n            print('==================================')\n            # login_common_driver.find_element_by_id('com.tnaot.newspro:id/rlMine').click()\n>           LoginPage(login_common_driver).input_phoneNumber(login_success_data[\"phoneNumber\"])\n\nTestCases\\test_login.py:31: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nPageObjects\\login_page.py:45: in input_phoneNumber\n    self.get_element(self.tv_login_btn).click()\nPageObjects\\BasePage.py:32: in get_element\n    ele = self.driver.find_element(*locator)\nvenv\\lib\\site-packages\\appium\\webdriver\\webdriver.py:282: in find_element\n    return self.execute(RemoteCommand.FIND_ELEMENT, {'using': by, 'value': value})['value']\nvenv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py:319: in execute\n    response = self.command_executor.execute(driver_command, params)\nvenv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py:374: in execute\n    return self._request(command_info[0], url, body=data)\nvenv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py:397: in _request\n    resp = self._conn.request(method, url, body=body, headers=headers)\nvenv\\lib\\site-packages\\urllib3\\request.py:79: in request\n    method, url, fields=fields, headers=headers, **urlopen_kw\nvenv\\lib\\site-packages\\urllib3\\request.py:170: in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\nvenv\\lib\\site-packages\\urllib3\\poolmanager.py:375: in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\nvenv\\lib\\site-packages\\urllib3\\connectionpool.py:756: in urlopen\n    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\nvenv\\lib\\site-packages\\urllib3\\util\\retry.py:532: in increment\n    raise six.reraise(type(error), error, _stacktrace)\nvenv\\lib\\site-packages\\urllib3\\packages\\six.py:734: in reraise\n    raise value.with_traceback(tb)\nvenv\\lib\\site-packages\\urllib3\\connectionpool.py:706: in urlopen\n    chunked=chunked,\nvenv\\lib\\site-packages\\urllib3\\connectionpool.py:445: in _make_request\n    six.raise_from(e, None)\n<string>:3: in raise_from\n    ???\nvenv\\lib\\site-packages\\urllib3\\connectionpool.py:440: in _make_request\n    httplib_response = conn.getresponse()\n..\\..\\Python3.7.2\\lib\\http\\client.py:1321: in getresponse\n    response.begin()\n..\\..\\Python3.7.2\\lib\\http\\client.py:296: in begin\n    version, status, reason = self._read_status()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <http.client.HTTPResponse object at 0x0000023377D15588>\n\n    def _read_status(self):\n        line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n        if len(line) > _MAXLINE:\n            raise LineTooLong(\"status line\")\n        if self.debuglevel > 0:\n            print(\"reply:\", repr(line))\n        if not line:\n            # Presumably, the server closed the connection before\n            # sending a valid response.\n>           raise RemoteDisconnected(\"Remote end closed connection without\"\n                                     \" response\")\nE           urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n\n..\\..\\Python3.7.2\\lib\\http\\client.py:265: ProtocolError"}, "steps": [{"name": "正常登录", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n", "trace": "  File \"D:\\software\\PycharmProject\\CMAPP003\\TestCases\\test_login.py\", line 31, in test_login_success\n    LoginPage(login_common_driver).input_phoneNumber(login_success_data[\"phoneNumber\"])\n  File \"D:\\software\\PycharmProject\\CMAPP003\\PageObjects\\login_page.py\", line 45, in input_phoneNumber\n    self.get_element(self.tv_login_btn).click()\n  File \"D:\\software\\PycharmProject\\CMAPP003\\PageObjects\\BasePage.py\", line 32, in get_element\n    ele = self.driver.find_element(*locator)\n  File \"D:\\software\\PycharmProject\\CMAPP003\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 282, in find_element\n    return self.execute(RemoteCommand.FIND_ELEMENT, {'using': by, 'value': value})['value']\n  File \"D:\\software\\PycharmProject\\CMAPP003\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 319, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"D:\\software\\PycharmProject\\CMAPP003\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 374, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"D:\\software\\PycharmProject\\CMAPP003\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 397, in _request\n    resp = self._conn.request(method, url, body=body, headers=headers)\n  File \"D:\\software\\PycharmProject\\CMAPP003\\venv\\lib\\site-packages\\urllib3\\request.py\", line 79, in request\n    method, url, fields=fields, headers=headers, **urlopen_kw\n  File \"D:\\software\\PycharmProject\\CMAPP003\\venv\\lib\\site-packages\\urllib3\\request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"D:\\software\\PycharmProject\\CMAPP003\\venv\\lib\\site-packages\\urllib3\\poolmanager.py\", line 375, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"D:\\software\\PycharmProject\\CMAPP003\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 756, in urlopen\n    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n  File \"D:\\software\\PycharmProject\\CMAPP003\\venv\\lib\\site-packages\\urllib3\\util\\retry.py\", line 532, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n  File \"D:\\software\\PycharmProject\\CMAPP003\\venv\\lib\\site-packages\\urllib3\\packages\\six.py\", line 734, in reraise\n    raise value.with_traceback(tb)\n  File \"D:\\software\\PycharmProject\\CMAPP003\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 706, in urlopen\n    chunked=chunked,\n  File \"D:\\software\\PycharmProject\\CMAPP003\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 445, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"D:\\software\\PycharmProject\\CMAPP003\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 440, in _make_request\n    httplib_response = conn.getresponse()\n  File \"D:\\software\\Python3.7.2\\lib\\http\\client.py\", line 1321, in getresponse\n    response.begin()\n  File \"D:\\software\\Python3.7.2\\lib\\http\\client.py\", line 296, in begin\n    version, status, reason = self._read_status()\n  File \"D:\\software\\Python3.7.2\\lib\\http\\client.py\", line 265, in _read_status\n    raise RemoteDisconnected(\"Remote end closed connection without\"\n"}, "start": 1618475815199, "stop": 1618475835366}], "parameters": [{"name": "login_common_driver", "value": "'YeShen'"}], "start": 1618475815199, "stop": 1618475835439, "uuid": "54d7bf94-24fd-4be7-8ae5-71d1fdfb9929", "historyId": "153c9a18e21fbdf14c797fd32c2fbd75", "testCaseId": "1646706a82f15219666aefd65e52b8d9", "fullName": "TestCases.test_login.TestLogin#test_login_success", "labels": [{"name": "story", "value": "登录成功"}, {"name": "feature", "value": "登录模块"}, {"name": "tag", "value": "@pytest.mark.usefixtures('login_common_driver')"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-MI5M7JM"}, {"name": "thread", "value": "12160-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}